name: Lunar Glow CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moon-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/moon-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moon-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/moon-frontend:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
