version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: moon-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: moon-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/moonphaseDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: moon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
